apiVersion: v1
kind: Service
metadata:
  name: whatismyipsvc
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatismyip
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: MyApp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: MyApp
    spec:
      containers:
      - image: roifgroup/whatismyip
        imagePullPolicy: Always
        name: whatismyip
